INSERT INTO [dbo].[Genre](Genre) VALUES
('alternative'),
('blues'),
('children''s music'),
('classical'),
('comedy'),
('country'),
('dance'),
('easy listening'),
('electronic'),
('folk'),
('hip-hop/rap'),
('industrial'),
('instrumental'),
('jazz'),
('latin'),
('metal'),
('new age'),
('opera'),
('pop'),
('disco'),
('progressive'),
('r&b'),
('reggae'),
('rock'),
('singer/songwriter'),
('soul'),
('soundtrack'),
('spoken word'),
('vocal'),
('world')