INSERT INTO dbo.Instrument([Instrument]) VALUES
('accordion'),
('acoustic guitar'),
('bagpipes'),
('banjo'),
('bass guitar'),
('bongo drums'),
('bugle'),
('cello'),
('clarinet'),
('cymbals'),
('drums'),
('electric guitar'),
('flute'),
('French horn'),
('harmonica'),
('harp'),
('keyboard'),
('maracas'),
('organ'),
('pan flute'),
('piano'),
('recorder'),
('saxophone'),
('sitar'),
('tambourine'),
('triangle'),
('trombone'),
('trumpet'),
('tuba'),
('ukulele'),
('violin'),
('xylophone'),
('bassoon'),
('castanets'),
('didgeridoo'),
('double bass'),
('gong'),
('harpsichord'),
('lute'),
('mandolin'),
('oboe'),
('piccolo'),
('viola')