INSERT INTO dbo.Label VALUES
('a cappella records'),
('a&e records'),
('a&m records'),
('a-f records'),
('a-musik'),
('abbey records'),
('abbott records'),
('abc classics'),
('abc dunhill records'),
('abc-paramount records'),
('abc records'),
('abco records'),
('abkco records'),
('able label'),
('abnak records'),
('abner records'),
('absolutely kosher records'),
('abstract logix'),
('abundant life ministries'),
('accent records'),
('accent records (us)'),
('ace fu records'),
('ace of clubs records'),
('ace of hearts records'),
('ace of hearts records (us)'),
('ace records (united kingdom)'),
('ace records (united states)'),
('ache records'),
('acid jazz records'),
('aco records'),
('acorn records'),
('acoustic disc'),
('acte prealable'),
('ad noiseam'),
('adam viii'),
('adeline records'),
('adelphi records'),
('aditya music'),
('advent records'),
('aegean records'),
('aeronaut records'),
('afm records'),
('afo records'),
('african museum'),
('aftermath entertainment'),
('aggro berlin'),
('agit-prop records'),
('agitprop! records'),
('aip records'),
('airport route recordings'),
('ajax records'),
('aladdin records'),
('alarma records'),
('albany records'),
('albert productions'),
('alchemy records (japan)'),
('alchemy records (u.s.)'),
('alcopop! records'),
('alegre records'),
('alert records'),
('alfa matrix'),
('alfa records'),
('alias records'),
('alien8 recordings'),
('alive records'),
('all around the world'),
('all ice records'),
('all the madmen records'),
('all platinum records'),
('all saints records'),
('all star records'),
('allalom music'),
('allido records'),
('alligator records'),
('almo sounds'),
('almost gold recordings'),
('alpha pup records'),
('alta records'),
('altarus records'),
('alternative tentacles'),
('am:pm records'),
('amarillo records'),
('amaru entertainment'),
('the amazing kornyfone record label'),
('ambiances magnetiques'),
('ambiel music'),
('ambitiouz entertainment'),
('ambush reality records'),
('american gramaphone'),
('american modern recordings'),
('american music records'),
('american record company'),
('american record corporation'),
('american recording productions'),
('american recordings (us)'),
('amha records'),
('amiga'),
('ammor records'),
('amos records'),
('ampex records'),
('amphetamine reptile records'),
('amplexus'),
('amusic'),
('amy records'),
('analekta'),
('anchor records'),
('and/oar'),
('andie records'),
('andmoresound'),
('angel air records'),
('angel music group'),
('angel records'),
('angelophone records'),
('angular recording corporation'),
('anhrefn records'),
('animetrax'),
('aniplex'),
('anjunabeats'),
('ankst'),
('ankstmusik'),
('anna records'),
('annette records'),
('another century records'),
('anova music'),
('anthem records'),
('anti-'),
('anti-creative records'),
('anticon records'),
('antilles records'),
('antone''s record label'),
('anxious records'),
('anyway records'),
('aozora records'),
('apegenine recordings'),
('apex records'),
('aphonia recordings'),
('apollo records (1921) (u.s.)'),
('apollo records (1928) (u.s.)'),
('apollo records (1944) (u.s.)'),
('apollo records (belgium)'),
('appian publications & recordings'),
('applause records'),
('apple records'),
('april/schneeball'),
('apt records'),
('aquarius records (canada)'),
('aquarius records (croatia)'),
('arabesque records'),
('arc records'),
('arch hill recordings'),
('archenemy record company'),
('archeophone records'),
('architecture label'),
('archive international productions'),
('arcola'),
('ardent records'),
('arena rock recording co.'),
('aretino records'),
('argo records (uk)'),
('argo records (u.s.)'),
('arhoolie records'),
('ariola records'),
('arista nashville'),
('arista records'),
('aristocrat records'),
('ark 21 records'),
('armada music'),
('around us entertainment'),
('artanis entertainment group'),
('artistdirect'),
('artistic records'),
('arto records'),
('artoffact records'),
('arts & crafts'),
('asbestos records'),
('ash international'),
('asian man records'),
('asphodel records'),
('asthmatic kitty records'),
('astralwerks'),
('astro magnetics'),
('asv records'),
('asylum records'),
('atavistic records'),
('atco records'),
('atic records'),
('atlantic jaxx'),
('atlantic records'),
('ato records'),
('atoll records'),
('atp recordings'),
('attack records (uk)'),
('attic records (canada)'),
('attitude records'),
('atypeek music'),
('au go go records'),
('audio antihero'),
('audio dregs'),
('audio fidelity records'),
('audio therapy'),
('audiobulb records'),
('audiogram'),
('audiophile records'),
('audition records'),
('aum fidelity'),
('authentic records'),
('autograph records'),
('autumn records'),
('ava recordings'),
('avang music'),
('avantgarde music'),
('avatar records'),
('avatar records (electronic)'),
('avco records'),
('avex trax'),
('avi records'),
('aviance records'),
('aware records'),
('awareness records'),
('azteca records'),
('azuli records'),
('b.o.s.s.'),
('b-unique records'),
('babel label'),
('baby records (italian label)'),
('babygrande records'),
('back beat records'),
('backporch revolution'),
('bad boy records'),
('bad taste'),
('bad taste records'),
('badorb.com'),
('balkan samba records'),
('balkanton'),
('bally records'),
('banda records'),
('bang records'),
('bangor records'),
('banner records'),
('bar/none records'),
('baratos afins'),
('barclay records'),
('barely breaking even'),
('barking hoop recordings'),
('barking pumpkin records'),
('barn records'),
('barnaby records'),
('barrelhouse records'),
('barsuk records'),
('basic beat recordings'),
('basic replay'),
('basick records'),
('baton records'),
('bayou teche brewery'),
('bbc radio collection'),
('bbc records'),
('bbr music group'),
('bc recordings'),
('bcore disc'),
('bear family records'),
('bearsville records'),
('beat factory'),
('beatservice records'),
('bec recordings'),
('bedazzled records'),
('bedrock records'),
('bedroom community'),
('the bedtime record'),
('beggars banquet records'),
('beka records'),
('bel-tone records'),
('bell records (1920s) (u.s.)'),
('bell records (1940) (u.s.)'),
('bell records (u.s. and u.k.)'),
('bella union'),
('bellaccord'),
('bellmark records'),
('below par records'),
('beltona records'),
('beluga heights records'),
('belvedere records'),
('benbecula records'),
('benson records'),
('berliner gramophone'),
('beserkley records'),
('bet-car records'),
('beta-lactam ring records'),
('bethlehem records'),
('better looking records'),
('beverley''s'),
('beyond records (u.k. 1992)'),
('beyond records (norway) (2011)'),
('beyond therapy records'),
('bi''n music'),
('bibletone records'),
('biddulph recordings'),
('bieler bros. records'),
('big bear records'),
('big beat records (ace subsidiary)'),
('big beat records (atlantic subsidiary)'),
('big brother recordings'),
('big cat records'),
('big dada'),
('big hit entertainment'),
('big life'),
('big machine records'),
('big neck records'),
('big orange clown records'),
('big records'),
('big rig records'),
('big time records'),
('big top records'),
('big tree records'),
('big up entertainment'),
('big vin records'),
('big wheel recreation'),
('biltmore records'),
('binge records'),
('bingola records'),
('biograph records'),
('birdman records'),
('bis records'),
('biscoito fino'),
('bitbird'),
('biv 10 records'),
('bizarre records'),
('black and greene records'),
('black & white records'),
('black hen music'),
('black hole recordings'),
('black jays'),
('black kapital records'),
('black mark production'),
('black market activities'),
('black patti records'),
('black pill red pill'),
('black saint/soul note'),
('black swan records'),
('black swan records (uk)'),
('black top records'),
('the black wall street records'),
('blackened recordings'),
('blackground records'),
('blackhouse records'),
('blackout records'),
('blacksmith records'),
('blast first'),
('blight. records'),
('block entertainment'),
('block starz music'),
('blocks recording club'),
('blonde vinyl'),
('blood and fire'),
('blood and ink records'),
('bloodline records'),
('bloodshot records'),
('bloodwork records'),
('bloody fist records'),
('blow the fuse records'),
('blue amberol records'),
('blue beat records'),
('blue cat records'),
('blue dog records'),
('blue goose records'),
('blue horizon'),
('blue jordan records'),
('blue lake records'),
('blue leaf music'),
('blue note records'),
('blue rock records'),
('blue room released'),
('blue thumb records'),
('bluebird records'),
('blues beacon records'),
('bluesanct records'),
('bluesville records'),
('bluesway records'),
('bme recordings'),
('bmg'),
('bmg heritage records'),
('bmg music canada'),
('bmg rights management'),
('bna records'),
('boardwalk records'),
('body head entertainment'),
('bomp! records'),
('boner records'),
('bong load custom records'),
('bonnier amigo music group'),
('bonnier gazell music'),
('bonsound records'),
('bonzai records'),
('boompa records'),
('boomtown records'),
('bop cassettes'),
('borderline records'),
('bpitch control'),
('bradley''s records'),
('brass tacks records'),
('brassland records'),
('brave wave productions'),
('breakbeat kaos'),
('breastfed recordings'),
('breezeway records'),
('bridge 9 records'),
('bridge records, inc.'),
('bright antenna'),
('brille records'),
('broadcast twelve records'),
('broadmoor records'),
('broadway records (1920s)'),
('broadway records (1947)'),
('broadway records (2012)'),
('broken records'),
('broken spoke records'),
('bronze records'),
('bros records'),
('brother records'),
('bruc records'),
('brunswick records'),
('brushfire records'),
('brutal panda records'),
('brute/beaute records'),
('bsd records'),
('btnh worldwide'),
('buddah records'),
('buddyhead records'),
('buena vista music group'),
('bulb records'),
('bullet records'),
('bumstead records'),
('bungalo records'),
('bureau b'),
('burger records'),
('burgundy records'),
('burning heart records'),
('burnt toast vinyl'),
('business deal records'),
('busted flat records'),
('busy bee'),
('butterfly recordings'),
('byg actuel'),
('byo records'),
('the c kunspyruhzy'),
('c4 records'),
('c.i.a. records'),
('c/z records'),
('cadence jazz records'),
('cadence records'),
('cadet records'),
('caedmon audio'),
('caff records'),
('calabash music'),
('caldo verde records'),
('cam (italy)'),
('cam entertainment (japan)'),
('camcor records'),
('cameo-kid'),
('cameo-parkway records'),
('cameo records'),
('camino records'),
('camp records'),
('canaan records'),
('canadian-american records'),
('candid records'),
('candle records'),
('candlelight records'),
('candy ass records'),
('candyrat records'),
('cantaloupe music'),
('cantora records'),
('capitol hill music'),
('capitol music group'),
('capitol records'),
('capricorn records'),
('captain oi! records'),
('captains of industry'),
('caravan of dreams productions'),
('carbon copy media'),
('cardinal records (1920s) (u.s.)'),
('cardinal records (1950s) (u.s.)'),
('cardinal records (1964) (belgium)'),
('cargo music'),
('cargo records (canada)'),
('cargo records (uk)'),
('caribou records'),
('carish'),
('carl lindstrom company'),
('carnival records'),
('caroline distribution'),
('caroline records (u.s. and u.k.)'),
('carpark records'),
('carrillo music'),
('casablanca records'),
('cash money records'),
('castle communications'),
('castle records (oregon)'),
('catbird records'),
('catfish records'),
('cause 4 concern recordings'),
('caustic eye productions'),
('cavalier records'),
('cavetone records'),
('cavity search records'),
('cbc records'),
('cbs masterworks records'),
('cbs records'),
('cedille records'),
('celestial recordings'),
('celluloid records'),
('celtic music'),
('celtophile records'),
('centaur records'),
('centricity music'),
('century media records'),
('century records'),
('chainsaw records'),
('chalfont records'),
('chalice'),
('challenge records (1920s) (u.s.)'),
('challenge records (1950s) (u.s.)'),
('challenge records (1994) (netherlands)'),
('chameleon'),
('chamillitary'),
('champion records (richmond, indiana)'),
('champion records (nashville, tennessee)'),
('champion records (uk)'),
('chance records'),
('chancellor records'),
('chandos records'),
('channel classics records'),
('chapel records'),
('chappelle and stinnette records'),
('chapter music'),
('charged records'),
('charisma records'),
('charly records'),
('chart records'),
('che trading'),
('cheap records'),
('checker records'),
('cheeky records'),
('cheetah records'),
('chelsea records'),
('chemikal underground'),
('cherry red'),
('cherrydisc records'),
('cherrytree records'),
('chesky records'),
('chess records'),
('chi sound records'),
('chichukai label'),
('chief records'),
('chimney sweep records'),
('china record corporation'),
('china records'),
('chiswick records'),
('chocolate city music'),
('chocolate frog records'),
('chopper city records'),
('christian faith recordings'),
('chrysalis records'),
('chunksaah records'),
('ci records'),
('cinepoly records'),
('cinevox'),
('cinnamon toast records'),
('circle records'),
('city centre offices'),
('city slang records'),
('claddagh records'),
('classic produktion osnabruck'),
('classics club'),
('claves records'),
('clay records'),
('clean feed records'),
('clean-up records'),
('cleopatra records'),
('cleveland international records'),
('clickpop records'),
('clj records'),
('clover records'),
('cls records'),
('clubbo records'),
('cmc international'),
('cobra records'),
('cock rock disco'),
('coconut records'),
('cocoon recordings'),
('codiscos'),
('coed records'),
('cold chillin'' records'),
('cold meat industry'),
('cold spring'),
('colgems records'),
('collectables records'),
('collector records'),
('collins classics'),
('colonial records'),
('colortone records'),
('colpix records'),
('columbia graphophone company'),
('columbia masterworks records'),
('columbia music entertainment'),
('columbia records'),
('combat records'),
('come organisation'),
('comedy central records'),
('command performance records'),
('command records'),
('commodore records'),
('compadre records'),
('compass records'),
('composers recordings, inc.'),
('compost records'),
('concert artist recordings'),
('concord music group'),
('concord records'),
('connoisseur society'),
('conqueror records'),
('conspiracy music'),
('constantinople records'),
('constellation records (disambiguation)'),
('contemode'),
('contemporary records'),
('continental records'),
('the control group'),
('cook records'),
('cooking vinyl'),
('cooltempo records'),
('copenhagen records'),
('copper creek records'),
('coral records'),
('cordless recordings'),
('cornerstone ras'),
('corona records'),
('coronet records'),
('corporate punishment records'),
('corpus christi records'),
('corwood industries'),
('cotillion records'),
('country turtle records'),
('cowboy records'),
('cp records'),
('crammed discs'),
('crank! records'),
('crass records'),
('crave records'),
('crd records'),
('cream records'),
('creation records'),
('creative vibes'),
('credential recordings'),
('creeping bent'),
('creole records'),
('crescent records'),
('cricket records'),
('criminal iq records'),
('crimson records'),
('croatia records'),
('crown records'),
('crunchy frog records'),
('crustacean records'),
('cruz records'),
('crydamoure'),
('crying sun records'),
('crypt records'),
('cryptogramophone records'),
('cti records'),
('cub records'),
('cube entertainment'),
('cube records'),
('cuca records'),
('cult records'),
('culture press'),
('cumberland records'),
('cuneiform records'),
('curb records'),
('curling legs'),
('curtom records'),
('curves music'),
('custard records'),
('cutting edge'),
('cybele records'),
('cypress records'),
('czar entertainment'),
('czyz records'),
('drk3m'),
('d records'),
('d-block records'),
('d.p.g. recordz'),
('d-town music group, inc.'),
('da lench mob records'),
('daemon records'),
('daesung entertainment'),
('daffodil records'),
('dallas records'),
('dais records'),
('damaged goods'),
('dame dash music group'),
('damnably'),
('damon records'),
('dana records'),
('dance mania'),
('dance to the radio'),
('dancing cat records'),
('dancing ferret'),
('dandelion records'),
('danger crue records'),
('dangerbird records'),
('dangerhouse records'),
('danse macabre records'),
('daptone records'),
('dare to care records'),
('dark horse records'),
('darkest labyrinth'),
('darla records'),
('data records'),
('dawn raid entertainment'),
('dawn records'),
('daylight records'),
('dayspring records'),
('db records'),
('dc flag records'),
('dc-jam records'),
('dcide'),
('de luxe records'),
('de wolfe music'),
('dead oceans records'),
('dead reckoning records'),
('deaf records'),
('death row records'),
('deathlike silence productions'),
('deathwish inc.'),
('debut records'),
('decaydance records'),
('decca records'),
('deceptive records'),
('decon records'),
('deconstruction records'),
('deep elm records'),
('deep krate recordingz'),
('deep shag records'),
('deep soul records'),
('def american'),
('def jam records'),
('def jam south'),
('defected records'),
('defiance records'),
('definitive jux'),
('defstar records'),
('dekema records'),
('del-fi records'),
('delerium records'),
('delicious vinyl'),
('delirium records'),
('delmark records'),
('delphine records'),
('deltasonic'),
('deluxe records'),
('demon records'),
('dental records'),
('dented records'),
('dependent music'),
('dependent records'),
('deptford fun city records'),
('deram records'),
('derby records'),
('derrty entertainment'),
('desert storm'),
('desoto records'),
('desperation records'),
('desto records'),
('deutsche grammophon'),
('deviant records'),
('dew process'),
('dewdrops records'),
('df music organization'),
('dfa records'),
('dftba records'),
('dgc records'),
('dial records (1946) (u.s.)'),
('dial records (1964) (u.s.)'),
('dial records (1998) (u.s.)'),
('dial records (1999) (germany)'),
('diamante music group'),
('diamond cut productions'),
('diamond records'),
('dice records (1950/60''s ny label)'),
('dick bros record company'),
('a different drum'),
('diffusion records'),
('digital hardcore recordings'),
('digsin'),
('dim mak records'),
('dimension records'),
('din of ecstasy records'),
('dine alone records'),
('dino entertainment'),
('diplomat records'),
('diplomat records (budget)'),
('dirtnap records'),
('dirty hit'),
('dirty records'),
('dirtybird records'),
('disa records'),
('dischord records'),
('discipline global mobile'),
('discodance'),
('discos fuentes'),
('discos taxco'),
('discos y cintas denver'),
('discovery records'),
('discreet records'),
('diskos'),
('diskoton'),
('disneyland records'),
('disorient records'),
('displeased records'),
('disques dreyfus'),
('disques victoire'),
('disques vogue'),
('distinct''ive breaks records'),
('distinct''ive records'),
('distort entertainment'),
('distribution select'),
('disturbing tha peace'),
('diva records'),
('diw records'),
('dixieland jubilee records'),
('djm records'),
('do it records'),
('doctor dream records'),
('document records'),
('dog meat records'),
('doggystyle records'),
('dogmatone'),
('dolores recordings'),
('dolphin music'),
('dolton records'),
('domino recording company (1993)'),
('domino records (1916-1917)'),
('domino records (1924-1934)'),
('domino records (1957-1961)'),
('domo records'),
('don giovanni records'),
('doomtree'),
('dope house records'),
('dore records'),
('dot dash recordings'),
('dot records'),
('double-time records'),
('double zero records'),
('doublemoon'),
('dovecote records'),
('downtown records'),
('drag city'),
('dragon records'),
('dragon street records'),
('drakkar entertainment'),
('drama records'),
('dramatico'),
('draper inc. records'),
('dreamboat records'),
('dreamville records'),
('dreamworks records'),
('drive-thru records'),
('driven music group'),
('dro records'),
('drog records'),
('drt entertainment'),
('drumcode records'),
('dsfa records'),
('dsn music'),
('dualtone records'),
('duck down records'),
('duck records'),
('ductape records'),
('duke records'),
('duke street records'),
('duna records'),
('dunhill records'),
('dunwich records'),
('duophonic records'),
('durium records'),
('dvs records'),
('dynamic'),
('dynamica'),
('dynovoice records'),
('e1 music'),
('e.g. records'),
('eagle records'),
('eagle rock entertainment'),
('eagle rock records'),
('earache records'),
('eardrum records'),
('early records'),
('earthly delights'),
('earwig music company'),
('east meets west music'),
('east side digital records'),
('east west records'),
('eastern conference records'),
('eastlawn records'),
('eaturmusic'),
('ebul'),
('echo records'),
('eclipse records'),
('ecm'),
('ecstatic peace!'),
('ecstatic yod'),
('ed banger records'),
('edel-mega records'),
('edel music'),
('edelweiss emission'),
('edison bell'),
('edison records'),
('edition lilac'),
('eenie meenie records'),
('eerie materials'),
('efm records'),
('egghunt records'),
('egrem'),
('eibon records'),
('ektaar music ltd'),
('el cartel records'),
('el puerto records'),
('elan recordings'),
('electric honey'),
('electrecord'),
('electrola'),
('elefant records'),
('elefant traks'),
('elektra records'),
('element 9'),
('elementree records'),
('elenco'),
('the elephant 6 recording company'),
('eleven: a music company'),
('eleven seven music'),
('eleveneleven'),
('ellahy amen records'),
('elypsia records'),
('em:t records'),
('emanem records'),
('emarcy records'),
('embassy records'),
('embryo records'),
('emerald music'),
('emerald records (1966)'),
('emerald records (2000s)'),
('emergency broadcast system records'),
('emergency records'),
('emerson records'),
('emi'),
('emi records'),
('emi america records'),
('emi-capitol special markets'),
('emi christian music group'),
('emi classics'),
('emi hemisphere'),
('emi latin'),
('emperor jones'),
('emperor norton records'),
('empire mates entertainment'),
('empreintes digitales'),
('end all life productions'),
('end records'),
('the end records'),
('endearing records'),
('energy rekords'),
('enigma records'),
('enjoy records'),
('ensign records'),
('enterprise records'),
('entertainment one music'),
('enzyme records'),
('epic records'),
('epidemic records'),
('epitaph records'),
('equal vision records'),
('equator records (canada)'),
('equator records (kenya)'),
('equity music group'),
('era records'),
('erased tapes records'),
('erato records'),
('eroica classical recordings'),
('eros music'),
('ersatz audio'),
('erstwhile records'),
('eskaton'),
('esl music'),
('esp-disk'),
('esquimaux management'),
('esquire records'),
('esquire records (uk)'),
('essential records (christian)')
go
INSERT INTO dbo.Label VALUES
('essential records (london)'),
('essex records'),
('estonian record productions'),
('estrus records'),
('esurient communications'),
('eternal records'),
('eulogy recordings'),
('eurodisc'),
('europa'),
('ever reviled records'),
('everest records'),
('everloving records'),
('excel records'),
('excello records'),
('excelsior recordings'),
('exceptional records'),
('executive music group'),
('exercise1 records'),
('exit records'),
('exodus records'),
('exploding in sound'),
('extasy records'),
('extensive music'),
('extreme records'),
('eye q'),
('eyeball records'),
('f-beat records'),
('f-ire collective'),
('facedown records'),
('factory records'),
('fader label'),
('failsafe records'),
('falcon records - subsidiary of vee-jay'),
('falcon records (canadian label)'),
('falcon records (texas)'),
('fall of the west records'),
('falling a records'),
('family tree records'),
('famous records'),
('fanfare records'),
('fania records'),
('fantastic plastic records'),
('fantasy records'),
('fascination records'),
('fast product'),
('fat cat records'),
('fat possum records'),
('fat wreck chords'),
('fatal recordings'),
('father/daughter records'),
('faultline records'),
('favored nations'),
('fax +49-69/450464'),
('fcommunications'),
('fearless records'),
('federal records'),
('fellside records'),
('felsted records uk'),
('fence records'),
('fenway recordings'),
('ferret music'),
('fervent records'),
('fervor records'),
('festival distribution'),
('festival records'),
('fever records'),
('fflach'),
('ffrr records'),
('fiction records'),
('fiddler records'),
('fidelity records'),
('fierce angel'),
('fierce panda records'),
('fifth colvmn records'),
('figure iv entertainment'),
('film score monthly'),
('filmguerrero'),
('filthy note'),
('filtro musik'),
('finger lickin'' records'),
('fingerprint records'),
('fire records (pakistan)'),
('fire records (uk)'),
('fire records (u.s.)'),
('firebox records'),
('first avenue records'),
('first terrace records'),
('fitamin un'),
('fixt music'),
('flair records'),
('flameshovel records'),
('flamingo recordings'),
('flashover recordings'),
('flashpoint music'),
('flawless records'),
('fledg''ling records'),
('flemish eye'),
('the flenser'),
('flicker records'),
('flip records (1950s)'),
('flip records (1994)'),
('flipmode entertainment'),
('fly records'),
('flying fish records'),
('flying nun records'),
('flying tart'),
('flyright records'),
('flyte tyme records'),
('fm records'),
('fmp (free music production)'),
('fmr records'),
('focus group holdings limited'),
('fog city records'),
('fogarty''s cove music'),
('folk-legacy records'),
('folkways records'),
('fonal records'),
('fondle''em records'),
('fonotipia records'),
('fonovisa records'),
('fontana records'),
('food records'),
('fool''s gold records'),
('fools of the world'),
('forced exposure'),
('forces of satan records'),
('the ford plant'),
('forefront records'),
('foreshadow'),
('formation records'),
('fort knocks entertainment'),
('fortissimo records'),
('fortuna pop!'),
('fortune records'),
('forward motion records'),
('four music'),
('fourth and broadway records'),
('fourth dimension records'),
('fowl records'),
('fox music'),
('fractured transmitter recording company'),
('fraternity records'),
('fre records'),
('freak recordings'),
('freakdance records'),
('fred records'),
('free dirt records'),
('free-will'),
('freedom from'),
('freedom records'),
('freeworld entertainment'),
('frenchkiss records'),
('fresh records (uk)'),
('fresh records (us)'),
('friendly fire recordings'),
('fringe product'),
('frog pad records'),
('frog records'),
('frontier records'),
('frontiers records'),
('frontline records (1980s)'),
('fsuk records'),
('fuel 2000'),
('fueled by ramen'),
('fueradeserie!'),
('full moon productions'),
('full moon records (us)'),
('full surface records'),
('full time hobby'),
('fullsteam records'),
('funk volume'),
('funtrip records'),
('fury records'),
('fusion records'),
('future classic'),
('future farmer records'),
('future records'),
('fysisk format'),
('g*59 records'),
('g-funk entertainment'),
('g-series'),
('g-unit records'),
('g7 welcoming committee records'),
('galaxy records'),
('galaxy21 music'),
('galilee of the nations'),
('galileo records'),
('gallo record company'),
('gamble records'),
('gan-shin'),
('gangsta advisory records'),
('gearhead records'),
('gee records'),
('gee street records'),
('geffen records'),
('gekko records'),
('general records'),
('genjing records'),
('gennett records'),
('geoma records'),
('gern blandsten records'),
('get low recordz'),
('geykido comet records'),
('ghetto ruff'),
('ghost box music'),
('ghostlight records'),
('ghostly international'),
('giant electric pea'),
('giant records'),
('giant step'),
('giantslayer records'),
('gifted records'),
('gigantic music'),
('giorno poetry systems'),
('giza studio'),
('glacial pace'),
('glasgow underground recordings'),
('glitch mode recordings'),
('glitterbeat records'),
('glitterhouse records'),
('global music group'),
('global trance network'),
('glowworm records'),
('glurp'),
('gma records'),
('gmm grammy'),
('gmt records'),
('gnomonsong'),
('gnp crescendo records'),
('go! beat records'),
('go-feet records'),
('go-kart records'),
('go-kustom rekords'),
('godzilla entertainment'),
('gold castle records'),
('gold label records'),
('gold mind records'),
('gold mountain records'),
('gold robot records'),
('gold standard laboratories'),
('gold star records'),
('gold typhoon'),
('golden era records'),
('golden world records'),
('goldenrod records'),
('the goldmind inc.'),
('goldwax records'),
('gone records'),
('goner records'),
('good entertainment'),
('good looking records'),
('good music'),
('good records'),
('good time jazz records'),
('good to die records'),
('good vibrations'),
('gooom disques'),
('gordy records'),
('gospocentric records'),
('gotee records'),
('gourd music'),
('grafton entertainment'),
('gramavision records'),
('gramm'),
('gramophone company'),
('granary music'),
('grand award records'),
('grand central records'),
('grand hustle records'),
('le grand magistery'),
('grand production'),
('grand royal'),
('grapefruit'),
('grappa music'),
('grateful dead records'),
('graveface records'),
('gravitas recordings'),
('gravity records'),
('great big mouth records'),
('greedhead music'),
('green cookie records'),
('green linnet records'),
('greenhouse music'),
('greensleeves records'),
('greentrax recordings'),
('gregmark records'),
('grenadine records'),
('grey gull records'),
('greyday productions'),
('griffin music'),
('gringo records'),
('groove records'),
('the groove thing'),
('grp records'),
('grrr records'),
('grunt records'),
('gto records'),
('guerilla records'),
('guided missile'),
('guitarmonk records'),
('gulcher records'),
('gun records'),
('gusto records'),
('gut records'),
('gutterth'),
('guy cloutier communications'),
('gwr records'),
('h&l records'),
('hachama'),
('hakatak international'),
('half a cow'),
('hallucination recordings'),
('hamburg records'),
('hamilton records'),
('hammock music'),
('hand drawn dracula'),
('handsome boy records'),
('hangars liquides'),
('hangman records'),
('hanna barbera records'),
('hannibal records'),
('hansa records'),
('hanson records'),
('happy couples never last'),
('happy happy birthday to me records'),
('happy tiger records'),
('happysad records'),
('hardwood records'),
('harlekijn'),
('harmolodics'),
('harmonia mundi'),
('harmony records'),
('harriet records'),
('harthouse'),
('harvest records'),
('hatchet house'),
('hathut records'),
('headhunter records'),
('hear music'),
('heart warming'),
('heartbeat records'),
('heartbeat records (bristol)'),
('hearts of space records'),
('heaven music'),
('heaven records'),
('heavenly records'),
('hed artzi music'),
('hed kandi'),
('hefty records'),
('heiress records'),
('heist or hit records'),
('helicon records'),
('hell, etc.'),
('hellcat records'),
('hellhound records'),
('hello cd of the month club'),
('hello cleveland!'),
('hep-me records'),
('her royal majesty''s records'),
('herald av publications'),
('herald records'),
('heritage records'),
('hermes records'),
('herwin records'),
('hevy devy records'),
('hi life recordings'),
('hi-n-dry'),
('hi or hey records'),
('hi records'),
('hib-tone'),
('hickory records'),
('hidden beach recordings'),
('hieroglyphics imperium recordings'),
('high dive records'),
('high street records'),
('high water recording company'),
('higher ground records'),
('higher octave'),
('higher state'),
('highland records'),
('hightone records'),
('hiljaiset levyt'),
('him international music'),
('hip records'),
('hip-o records'),
('hipposonic studios'),
('his master''s voice'),
('historic masters'),
('historical records'),
('hit of the week records'),
('hobbledehoy record co.'),
('holiday inn records'),
('holiday records'),
('hollywood records'),
('holy roar records'),
('home sweet home records'),
('homespun records'),
('homestead records'),
('homestead records (1920s)'),
('honest don''s records'),
('honest jon''s'),
('hoo-bangin'' records'),
('hope music group'),
('hope recordings'),
('hopeless records'),
('hopestreet recordings'),
('horizon records'),
('horris records'),
('horror house entertainment.'),
('hosanna! music'),
('hospital records'),
('hoss records'),
('hot pot music'),
('hot wax records'),
('how''s that music'),
('hugpatch records'),
('human imprint'),
('humming bird records'),
('hungaroton'),
('hush records'),
('hushush'),
('hut records'),
('hwem'),
('hybris'),
('hydra head records'),
('hyperdub'),
('hyperion records'),
('hyperium records'),
('hypertek digital'),
('hypnos'),
('hypnotize minds'),
('hapna'),
('i'),
('i.r.s. records'),
('i scream records'),
('iamsound records'),
('ice age entertainment'),
('ice records'),
('ici, d''ailleurs...'),
('icon records'),
('idea records'),
('ideal records'),
('idol records'),
('iii records'),
('ill.skillz recordings'),
('ill will records'),
('illegal art'),
('illegal musik'),
('illegal records'),
('illuminating technologies'),
('imagen records'),
('imaginary records'),
('immediate records'),
('immortal records'),
('impact (new zealand)'),
('impact records'),
('impact records (california)'),
('imperial records (1900) (u.s.)'),
('imperial records (1920) (u.k.)'),
('imperial records (1947 and 2006 u.s.)'),
('imprint records'),
('impulse! records'),
('imputor?'),
('in-fidelity recordings'),
('in records (united states)'),
('in records (australia)'),
('in the red records'),
('the inc. records'),
('incentive records'),
('incredible'),
('incus records'),
('indecision records'),
('independiente records'),
('indestructible record company'),
('indi script records'),
('indianola records'),
('indirecto records'),
('industrial records'),
('infectious records'),
('infinity cat recordings'),
('infinity recordings'),
('infrared'),
('initial records'),
('inner ear'),
('innocent records'),
('innova recordings'),
('ino records'),
('inoxia records'),
('inpop records'),
('inside recordings'),
('insideout music'),
('insideout us'),
('instant karma'),
('instinct records'),
('intec digital'),
('integrity records'),
('intense records'),
('interactive jack records'),
('international artists'),
('international deejay gigolo records'),
('interphon records'),
('interscope-geffen-a&m'),
('interscope records'),
('intrada records'),
('invictus records'),
('invisible agent'),
('invisible hands music'),
('invisible records'),
('invogue records'),
('iodine recordings'),
('iona records'),
('ipecac recordings'),
('ironworks'),
('isadora records'),
('island blue records'),
('the island def jam music group'),
('island masters'),
('island records'),
('island reggae greats'),
('ivy league records'),
('ivy queen musa sound'),
('j & s records'),
('j records'),
('j storm'),
('j.o.b. records'),
('jackson records'),
('jad records'),
('jade tree records'),
('jagjaguwar'),
('jahtari'),
('jamaican gold'),
('jamie records'),
('janus records'),
('jaro medien'),
('jarrah records'),
('jarring effects'),
('jasmine records'),
('jaus records'),
('javotti media'),
('jaxart records (u.s.)'),
('jay boy'),
('jay-jay records'),
('jaytee records'),
('jazz, ltd.'),
('jazz man records'),
('jazzaway records'),
('jazzland records (1960) (u.s.)'),
('jazzland records (1997) (norway)'),
('jazzology records'),
('jdub records'),
('jeepster records'),
('jehova-nisi producciones'),
('jellyfish entertainment'),
('jemp records'),
('jerden records'),
('jericho beach music'),
('jester records'),
('jesuit music ministry'),
('jet records'),
('jet set records'),
('jetydosa'),
('jewel records (cincinnati, ohio)'),
('jewel records (new york)'),
('jewel records (shreveport, louisiana)'),
('jewel runners'),
('jiggiri records'),
('jim henson records'),
('jimmy franks recording company'),
('jive electro'),
('jive records'),
('jmt records'),
('joe & joey records'),
('johann''s face records'),
('johnny & associates'),
('joilicious records'),
('jolly roger records'),
('josie records'),
('joyful noise recordings'),
('jsp records'),
('juana records'),
('jubilee records'),
('judd records'),
('judgement records'),
('jugoton'),
('juice box records'),
('juke box records'),
('jumbo records'),
('jump records'),
('jungle records'),
('junior boy''s own'),
('justablip records'),
('jyp entertainment'),
('k&k verlagsanstalt'),
('k records'),
('k-bahn'),
('k-tel records'),
('kahvi'),
('kaifa records'),
('kairos'),
('kalakuta republic'),
('kalan muzik'),
('kama sutra records'),
('kanine records'),
('kapow records'),
('kapp records'),
('karmageddon media'),
('kedar records'),
('keen records'),
('kelp records'),
('kemado records'),
('kemosabe records'),
('kennis music'),
('kent records'),
('key sounds label'),
('ki/oon music'),
('kickball records'),
('kicking mule records'),
('kid stuff records'),
('kiddyphone'),
('kill rock stars'),
('kimi records'),
('kindercore records'),
('kinetic records'),
('king records (japan)'),
('king records (usa)'),
('king worldwide'),
('kirtland records'),
('kitchen motors'),
('kitchenware records'),
('kitsune music'),
('kitty kitty corporation'),
('kitty play records'),
('kitty-yo'),
('klf communications'),
('kmb jazz'),
('knee deep records'),
('knitting factory records'),
('knockout entertainment'),
('koch distribution'),
('koch entertainment'),
('koch entertainment canada'),
('koch international records'),
('koch publishing'),
('kokomo records'),
('kompakt'),
('kon live distribution'),
('konichiwa records'),
('kontor records'),
('konvict muzik'),
('koolarrow records'),
('korova'),
('kranky'),
('kross over entertainment'),
('kscope'),
('kung fu records'),
('kvitnu'),
('la tribu'),
('label fandango'),
('labrador records'),
('laface records'),
('laff records'),
('lakeshore records'),
('lakeside records'),
('lamon records'),
('lanor records'),
('lasalle records'),
('last gang records'),
('latent recordings'),
('latino buggerveil'),
('laundry label'),
('laurie records'),
('lava records'),
('le grand magistery'),
('leader records (uk)'),
('leader records (us)'),
('leaf hound records'),
('the leaf label'),
('leathur records'),
('leedon records'),
('leeds talk-o-phone'),
('leesta vall'),
('lefrak-moelis records'),
('legacy recordings'),
('legion records'),
('legit ballin'''),
('lench mob records'),
('lengua armada discos'),
('lens records'),
('les disques du crepuscule'),
('level plane'),
('lex records'),
('lhi records'),
('liberation music'),
('liberation records'),
('liberty & lament'),
('liberty music shop records'),
('liberty records'),
('library records'),
('licking fingers'),
('lifeforce records'),
('light organ records'),
('light records'),
('lil'' chief records'),
('limb music'),
('limelight records'),
('limp records'),
('lincoln records'),
('lingasong records'),
('linn records'),
('linus entertainment'),
('lion music'),
('lioness records'),
('lionheart music group'),
('liquor and poker music'),
('listenable records'),
('lithium'),
('little david records'),
('little marvel'),
('little wonder records'),
('lizard'),
('lizard king records'),
('lo-fidelity records'),
('lo recordings'),
('load records'),
('loaded records'),
('lobster records'),
('loca records'),
('locked on records'),
('locomotive music'),
('locust music'),
('loen entertainment'),
('lofton creek records'),
('logo records'),
('lojinx'),
('london records'),
('london-sire records'),
('lonely astronaut records'),
('lonesome day records'),
('longhorn records'),
('longines symphonette society'),
('loningisa'),
('looking glass workshop'),
('lookout! records'),
('looq records'),
('loose music'),
('loose records & music'),
('losen records'),
('lost & lonesome recording co.'),
('lost highway records'),
('lost language'),
('lotuspike'),
('loud records'),
('love is my velocity'),
('love minus zero recordings'),
('love police records'),
('love records'),
('lovecat music'),
('lovely music'),
('loveway records'),
('a low hum'),
('low life records'),
('low transit industries'),
('lowercase people records'),
('lrrc (luddite rural recording cooperative)'),
('ltm recordings'),
('lu pine records'),
('luaka bop'),
('lucid records'),
('lucidsamples'),
('lucky eleven records'),
('lucky four records'),
('lucky records'),
('lujo records'),
('luke records'),
('lumiere records'),
('lyric records (germany)'),
('lyric records (us)'),
('lyric street records'),
('lyrita recorded edition'),
('m3 records'),
('m.a.c.e. music'),
('m&g records'),
('machete music'),
('machine shop recordings'),
('machinery records'),
('mad decent'),
('mad dragon records'),
('madhouse records'),
('madison records'),
('madison gate records'),
('magic bullet records'),
('magic circle music'),
('magna carta records'),
('magnanimous records'),
('magnatune'),
('magnet records'),
('magpie records'),
('mailboat records'),
('mainstream records'),
('mainya music'),
('maison de soul'),
('majestic record corporation'),
('majestic records'),
('majik ninja entertainment'),
('major league productions (mlp)'),
('major minor records'),
('major records (germany)'),
('mala records'),
('malaco records'),
('mam records'),
('mamlish records'),
('mammoth records'),
('mango records'),
('manhattan records'),
('manifesto records'),
('manifold records'),
('manimal vinyl'),
('manna music inc'),
('manor records'),
('man''s ruin records'),
('manticore records'),
('mantra recordings'),
('manyc records'),
('maplemusic recordings'),
('maranatha! music'),
('marian records'),
('mariann grammofon ab'),
('marina records'),
('marine parade records'),
('market square records'),
('marlin records'),
('marmalade records'),
('marrakesh records'),
('marriage records'),
('marsalis music'),
('mas flow inc'),
('mascot records'),
('mash down babylon records'),
('mass appeal records'),
('mass mvmnt'),
('massacre records'),
('mastercharge records'),
('masters of hardcore'),
('masterworks broadway records'),
('masterworks records'),
('matador records'),
('matty grooves records'),
('mau5trap'),
('mavin records'),
('maverick records'),
('maxi records'),
('maybach music group'),
('mca nashville records'),
('mca records'),
('medallion records'),
('mediarts records'),
('mediaskare records'),
('medium productions'),
('mega records'),
('megaforce records'),
('megalith records'),
('megarock records'),
('mego'),
('mello music group'),
('melodeon records'),
('melodic revolution records'),
('melodiya'),
('melotone records (australia)'),
('melotone records (us)'),
('meltdown records'),
('memento materia'),
('memorandum recordings'),
('memory lane music group'),
('memphis industries'),
('menart records'),
('the meny-x'),
('merciful release'),
('merck records'),
('mercury nashville records'),
('mercury records'),
('merge records'),
('meridian records'),
('meritt records'),
('mermaid records'),
('merovingian music'),
('messenger records'),
('metal blade records'),
('metal heaven'),
('metal mind productions'),
('metalheadz'),
('metascope records'),
('meteor records'),
('meteorcity records'),
('metro records'),
('metroplex'),
('metropolis records'),
('mfs'),
('mgm distribution'),
('mgm records'),
('microphone records'),
('midas records nashville'),
('middle pillar presents'),
('midhir records'),
('midi:nette records'),
('midijum records'),
('midland international records'),
('mighty atom records'),
('mighty force records'),
('mikroton recordings'),
('milan entertainment'),
('milan records'),
('milestone records'),
('the militia group'),
('mille pattes records'),
('mille plateaux'),
('millennium records'),
('mimosa'),
('minimal wave'),
('ministry of sound'),
('minit records'),
('minotauro records'),
('mint records'),
('mint 400 records'),
('minty fresh'),
('minus'),
('miracle revival recordings'),
('mirage records'),
('misfits records'),
('misra records'),
('missing link records'),
('mission records'),
('mistletone'),
('mixpak records'),
('mld entertainment (formerly duble kick company)'),
('mnemosyne productions'),
('mo-da-mu'),
('mo'' hits records'),
('mo'' wax'),
('mobile fidelity sound lab'),
('moda records'),
('mode records'),
('modern outsider'),
('modern records'),
('modular recordings'),
('moist music'),
('mojo records'),
('mokum records'),
('mom + pop music'),
('monarc entertainment'),
('mondo music corporation'),
('mondo records'),
('monika enterprise'),
('monitor records (new york)'),
('mono vs stereo'),
('monstercat'),
('montalban hotel'),
('montauk mantis'),
('monument records'),
('moon ska records'),
('moon ska world'),
('mooncrest records'),
('moonfog productions'),
('moonglow records'),
('the moonshine conspiracy'),
('moonshine music'),
('mordam records'),
('morr music'),
('morrison records (australia)'),
('morrison records (seattle)'),
('mortarhate records'),
('mosaic records'),
('moseley shoals records'),
('moshi moshi records'),
('moshpit tragedy records'),
('mosley music group'),
('motley records'),
('motor music records'),
('motown records'),
('mountain apple company'),
('mountain fever records'),
('mountain home records'),
('mountain records'),
('mouseville'),
('move records'),
('moving shadow'),
('mr bongo records'),
('mr. lady records'),
('mt. fuji records'),
('mtm records'),
('mudhoney records'),
('mulatta records'),
('multiply records'),
('multitone records'),
('mums records'),
('murder inc. records'),
('murderecords'),
('murmur'),
('musart records')
go
INSERT INTO dbo.Label VALUES
('musea'),
('mush records'),
('mushroom records (australia)'),
('mushroom records (canada)'),
('music brokers'),
('the music cartel'),
('music for nations'),
('music for pleasure'),
('music from the corner'),
('music maker'),
('music of life'),
('music west records'),
('music70'),
('musica omnia'),
('musical freedom'),
('musicmasters records'),
('musicor records'),
('musicraft records'),
('musidisc'),
('mutant league records'),
('mutant pop records'),
('mute records'),
('mvb records'),
('my pal god records'),
('the mylene sheath'),
('myrrh records'),
('myspace records'),
('mystic records'),
('n-coded music'),
('n5md'),
('nacional records'),
('naked records'),
('napalm records'),
('nappy boy'),
('narada productions'),
('nardis records'),
('narita records'),
('narnack records'),
('nation records'),
('national music lovers records'),
('national recording corporation'),
('national records'),
('native language music'),
('native records'),
('naxos records'),
('naxos world'),
('neat records'),
('necropolis records'),
('nega network'),
('neighborhood records'),
('nein records'),
('nemesis records'),
('nems enterprises (argentina)'),
('neon gold records'),
('neptune records'),
('nervous records (u.k.)'),
('nervous records (u.s.)'),
('netmusiczone records'),
('nettwerk'),
('network 23'),
('network records'),
('neurot recordings'),
('neutral records'),
('new alliance records'),
('new amsterdam records'),
('new earth records'),
('new european recordings'),
('new orleans records'),
('new red archives'),
('new renaissance records'),
('new wave productions'),
('new west records'),
('newhouse records'),
('newmemorabilia records'),
('nexsound'),
('next plateau records'),
('nextera'),
('ngoma'),
('nick records'),
('nicola delita'),
('nicotine records'),
('niezalezna oficyna wydawnicza cdn'),
('nighthawk records'),
('nightshade productions'),
('nihilist records'),
('nilaihah records'),
('nimfa sound'),
('ninja tune'),
('nitro records'),
('nixa records'),
('nmc music'),
('no fans records'),
('no fashion records'),
('no idea records'),
('no limit records'),
('no masters'),
('no milk records'),
('no records'),
('no remorse records'),
('nocopyrightsounds'),
('noh poetry records'),
('the noise company'),
('noise records'),
('noisebox records'),
('nonesuch records'),
('norcd'),
('nordic steel'),
('nordskog records'),
('noriq records'),
('northern records'),
('northernblues music'),
('northside'),
('northwestside records'),
('norton records'),
('not lame recordings'),
('nothing records'),
('nova zembla'),
('novamute records'),
('now-again records'),
('npg records'),
('ntone'),
('ntt publishing co.'),
('nuclear blast'),
('nude records'),
('nukleuz'),
('numa records'),
('nuphonic'),
('nux organization'),
('oasis records'),
('obese records'),
('oblivion records'),
('obr records'),
('octone records'),
('odd future records'),
('ode records'),
('odeon records'),
('off beat'),
('off centaur publications'),
('og music'),
('oglio records'),
('ogopa djs'),
('ogun records'),
('oh boy records'),
('oi! the boat records'),
('okeh records'),
('old europa cafe'),
('old homestead records'),
('oldies-33'),
('oldies-45'),
('oliver sudden productions'),
('olivia records'),
('om records'),
('omnivore recordings'),
('on-u sound records'),
('onclassical'),
('ondine'),
('one big spark'),
('one eleven records'),
('one little indian records'),
('one records (scotland)'),
('one records (serbia)'),
('one way records'),
('open bar entertainment'),
('open road recordings'),
('open sky records'),
('open world entertainment'),
('opera rara'),
('operaphone records'),
('opus records'),
('or records'),
('orange record label'),
('orange records'),
('orange twin records'),
('the orchard'),
('orchid tapes'),
('orfeo'),
('orfeon'),
('origin jazz library'),
('original blues classics'),
('original jazz classics'),
('original sound'),
('oriole records (uk)'),
('oriole records (u.s.)'),
('orion records'),
('orpheus music'),
('osmose productions'),
('out of line music'),
('outlaw recordz'),
('outpunk'),
('output recordings'),
('outside music'),
('outta sight records'),
('ovation records'),
('overcoat recordings'),
('ovo sound'),
('ovum recordings'),
('owl studios'),
('owsla'),
('oxford records'),
('oxide entertainment'),
('oxrecs digital'),
('oxygen music works'),
('p572'),
('pablo records'),
('pacific front recordings'),
('pacific jazz records'),
('pagan records'),
('page one records'),
('paid in full entertainment'),
('painted smiles'),
('paisley park records'),
('palette records'),
('palm pictures'),
('palm records'),
('palo duro records'),
('pan'),
('panart records'),
('pandisc records'),
('pangea recordings'),
('panhellenion records'),
('panic button records'),
('panorama records'),
('panton records'),
('panzerfaust records'),
('paper and glue'),
('paper bag records'),
('papillion records'),
('paracadute'),
('parachute records'),
('paramount records'),
('paramount records (1969)'),
('parasol records'),
('park records'),
('parkwood entertainment'),
('parlophone'),
('parrot records'),
('parrot records (chicago)'),
('partee records'),
('partisan records'),
('pasadena records'),
('pathe records'),
('patuxent music'),
('paw tracks'),
('peacefrog records'),
('peaceville records'),
('peacock records'),
('peak records'),
('peanuts & corn records'),
('pearl records'),
('peerless records'),
('penalty records'),
('pendragon records'),
('pendu sound recordings'),
('penny farthing records'),
('pentatone'),
('people mountain people sea'),
('people records'),
('pepper records'),
('perfect game recording co.'),
('perfect records'),
('perfecto records'),
('perhaps transparent'),
('perishable records'),
('perlon'),
('perspective records'),
('peter pan records'),
('pgp-rtb'),
('pgp-rts'),
('phantasy sound'),
('phantom city studios'),
('phantom records'),
('pharmacy records'),
('phase 4 stereo'),
('phi-dan records'),
('phil spector international'),
('philadelphia international records'),
('philips classics records'),
('philips records'),
('philles records'),
('phillips international records'),
('philly groove records'),
('philo records (folk)'),
('philo records (rhythm & blues)'),
('phono-cut record company'),
('phonogenic records (uk)'),
('phonogram records'),
('photo finish records'),
('pi recordings'),
('pias recordings'),
('piccadilly records'),
('piccolo town'),
('pickled egg records'),
('pickwick records'),
('piedmont records'),
('pigs whisker music'),
('pilz'),
('pina records'),
('pinecastle records'),
('pink and black records'),
('pinnacle records'),
('pipeline music'),
('pivotal rockordings'),
('placid casual'),
('plainisphare'),
('plaka pilipino'),
('plan 9 records'),
('plan-it-x records'),
('planet dog'),
('planet mu'),
('planet pimp records'),
('plant life records'),
('plantation records'),
('plasma records'),
('plastic raygun'),
('plastiq musiq'),
('platform records'),
('platipus records'),
('play it again sam'),
('play me'),
('playground music scandinavia'),
('playhouse records'),
('playing with sound'),
('playmaker music'),
('playtone'),
('pledis entertainment'),
('plug research'),
('plus 8'),
('pluto records'),
('pneuma recordings'),
('pof music'),
('point blank records'),
('point music'),
('poison ivy'),
('polar music'),
('polen records'),
('polo grounds music'),
('polydor records'),
('polygon records'),
('polygram'),
('polymorph records'),
('polyvinyl record co.'),
('pompeii records'),
('ponca jazz records'),
('pony canyon'),
('popfrenzy'),
('popsicle records'),
('poptones'),
('pork recordings'),
('portrait records'),
('posh boy records'),
('positiva records'),
('positive tone'),
('positron! records'),
('post records'),
('the post war blues'),
('postcard records'),
('potential getaway driver'),
('power it up records'),
('power out'),
('pravda records'),
('prawn song records'),
('precision talent'),
('prelude records'),
('president records'),
('pressure sounds'),
('prestige records'),
('prikosnovenie'),
('primary music'),
('priority records'),
('priory records'),
('prism records'),
('private music'),
('private stock records'),
('pro era records'),
('probe plus'),
('probe records'),
('procrastinate! music traitors'),
('production house records'),
('profane existence records'),
('profile entertainment'),
('profile records'),
('profile records (chief records subsidiary)'),
('profound lore records'),
('progrock records'),
('project blowed'),
('projekt records'),
('propeller recordings'),
('propeller records'),
('propeller records (boston)'),
('prophecy productions'),
('prophet entertainment'),
('prosthetic records'),
('protest records'),
('provogue records'),
('prt records'),
('ps classics'),
('p.s.f. records'),
('psi records'),
('psy-harmonics'),
('psycho+logical-records'),
('psychomania records'),
('psychonaut records'),
('psychopathic records'),
('psychout records'),
('punk core records'),
('purchase records'),
('pure steel records'),
('puritan records'),
('purple feather records'),
('purple music switzerland'),
('purple records'),
('purple ribbon records'),
('pusa inc.'),
('putumayo world music'),
('pwl'),
('pye golden guinea records'),
('pye international records'),
('pye records'),
('pyramid gang records'),
('q division records'),
('qn5 music'),
('qrs records'),
('qualiton'),
('qualiton records'),
('quality control music'),
('quality records'),
('quango music group'),
('quannum projects'),
('quarterstick records'),
('que-so records'),
('queen bee entertainment'),
('queen records'),
('quiet storm records'),
('quinlan road'),
('quirkworks laboratory discs'),
('quote unquote records'),
('qwest records'),
('r&s records'),
('rabid records'),
('racetrack records'),
('radar records'),
('radiant future records'),
('radiex records'),
('radikal records'),
('radioactive records'),
('ragged flag'),
('ragnarock'),
('rainbow records'),
('rainy day records'),
('rajon music group'),
('rak records'),
('ralph records'),
('ram records (uk)'),
('ram records (us)'),
('rama records'),
('randm records'),
('range life records'),
('ranwood records'),
('rap-a-lot records'),
('ras records'),
('rasa music'),
('raster-noton'),
('raucous records'),
('raven records'),
('ravenous records'),
('raw energy records'),
('rawkus records'),
('razor & tie'),
('razzia records'),
('rca camden'),
('rca/jive label group'),
('rca records'),
('rca red seal records'),
('rca victrola'),
('re-constriction records'),
('re-up records'),
('reach records'),
('react music limited'),
('reaction records'),
('ready records'),
('real talk entertainment'),
('real world records'),
('rebel records'),
('rebelle records'),
('rebelles europeens'),
('recess records'),
('recommended records'),
('recorded in hollywood'),
('recorte records'),
('recrec music'),
('red beet records'),
('red bird records'),
('red bull records'),
('red eye records'),
('red girl records'),
('red hammer records'),
('red house records'),
('red melon records'),
('red pajamas records'),
('red robin records'),
('red rooster records'),
('red star records'),
('redline records'),
('redone records'),
('reel life productions'),
('reflective records'),
('reflex records'),
('reflex/wolfpack records'),
('refuge records'),
('regain records'),
('regal records (1914) (uk)'),
('regal records (1920) (spain)'),
('regal records (1921) (us)'),
('regal records (1949) (us)'),
('regal zonophone records'),
('regency records'),
('regent records (uk)'),
('regent records (us)'),
('reinforced records'),
('rejoice records'),
('rekabet records'),
('rekords rekords'),
('relapse records'),
('relativity records'),
('releasing eskimo'),
('relentless records'),
('remedy records (uk)'),
('remedy records (us)'),
('remington-morse records'),
('remington records'),
('remote control records'),
('renaissance'),
('renaissance recordings'),
('repeat records'),
('repertoire records'),
('rephlex records'),
('reprise records'),
('republic records'),
('resipiscent'),
('resist music'),
('resistance records'),
('resonance records'),
('restless records'),
('rethink'),
('retroactive records'),
('reunion records'),
('rev-ola records'),
('reveal records label'),
('revealed recordings'),
('revelation records'),
('revenant records'),
('reverb records'),
('reverberation'),
('the reverberation appreciation society'),
('revival records'),
('revolution records'),
('r.e.x. records'),
('rex records (1912) (us)'),
('rex records (1933) (uk)'),
('rex records (1957) (us)'),
('rex records (2001) (uk)'),
('rfugrey'),
('rhino entertainment'),
('rhymesayers entertainment'),
('rhythm king'),
('rhythm zone'),
('rice music'),
('rich forever music'),
('ridge runner records'),
('righteous babe records'),
('rikos records'),
('riot city records'),
('ripete records'),
('ripple music'),
('rise above records'),
('rise records'),
('rising tide records'),
('riva records'),
('river jones music'),
('riverside records'),
('rko/unique records'),
('rmm records & video'),
('roadrunner records'),
('robbins entertainment'),
('robot needs home'),
('robotic empire'),
('rob''s house records'),
('rob''s records'),
('roc-a-fella records'),
('roc-la-familia'),
('roc nation'),
('rock action records'),
('rock bottom entertainment'),
('rock-o-rama'),
('rock records'),
('rock ridge music'),
('rocket girl'),
('the rocket record company'),
('rocket records'),
('rocketown records'),
('rockland records'),
('rodven records'),
('rogue music alliance'),
('roir'),
('rolling stones records'),
('romeo records'),
('romophone'),
('ron johnson records'),
('rooart'),
('roost records'),
('rooster blues'),
('ropeadope records'),
('rostrum records'),
('roswell'),
('rotana'),
('rotorelief'),
('rotters golf club'),
('rough trade records'),
('roule'),
('roulette records'),
('rounder records'),
('route 66 records'),
('rowdy records'),
('roxy recordings'),
('royalty records'),
('rpm records (united kingdom)'),
('rpm records (united states)'),
('rrrecords'),
('rs music'),
('rso records'),
('rubber jungle records'),
('ruby records'),
('rude records'),
('ruf records'),
('ruff ryders entertainment'),
('ruffhouse records'),
('ruffnation records'),
('run for cover records'),
('rune grammofon'),
('rural rhythm records'),
('rushmore records'),
('russell simmons music group'),
('rust records, ny'),
('rust nashville'),
('ruthless records'),
('ruthless records (chicago)'),
('rykodisc'),
('s. carter records'),
('s-curve records'),
('s.m. entertainment'),
('s2 records'),
('s2s pte. ltd.'),
('sabre records'),
('sacred bones records'),
('sacred records'),
('saddle creek records'),
('safehouse records'),
('sain'),
('saja records'),
('salsoul records'),
('salted music'),
('samadhi sound'),
('sanctuary records'),
('san francisco records'),
('sandy records'),
('sappy records'),
('sar records'),
('sarah records'),
('sarathan records'),
('saravah'),
('saregama'),
('sargent house'),
('satellite records'),
('savannah records'),
('savoy records'),
('savvy records'),
('saw recordings'),
('sbk records'),
('scantraxx recordz'),
('scared records'),
('scarlet records'),
('scat records'),
('scepter records'),
('schematic records'),
('schirmer records'),
('schism records'),
('sci fidelity records'),
('science friction'),
('scion audio/visual'),
('scitron'),
('scotti brothers records'),
('scratchie records'),
('screwgun records'),
('season of mist'),
('seclusiasis'),
('secret city records'),
('secret records'),
('secretly canadian'),
('secrets of sound'),
('sedimental'),
('see for miles records'),
('see thru broadcasting'),
('seed records'),
('seeland records'),
('selectric records'),
('selegna records'),
('self immolation'),
('sequel records'),
('seraphim records'),
('serio controla records'),
('serious business records'),
('serjical strike records'),
('service'),
('setanta records'),
('seventh level records'),
('seventh rule recordings'),
('several reasons'),
('severn records'),
('sh-k-boom records'),
('shadow records'),
('shady records'),
('shanachie records'),
('sheeba records'),
('sheer sound'),
('shelflife records'),
('shelter records'),
('shifty records (south africa)'),
('shifty records (usa)'),
('shimmy disc'),
('shinkansen records'),
('shitkatapult'),
('sho''nuff records'),
('shock records'),
('shogun audio'),
('shoreline records'),
('shout records'),
('show dog nashville'),
('shrapnel records'),
('shrimper records'),
('sic squared records'),
('sick room records'),
('side one recordings'),
('sidecho records'),
('sideonedummy records'),
('sidewalk records'),
('sierra records'),
('sigma editions'),
('signature records'),
('signature sounds recordings'),
('silas records'),
('silence records'),
('silkheart records'),
('silver planet'),
('silvertone records (1905) (us)'),
('silvertone records (1980) (uk)'),
('silvertone records (selfridges) (uk)'),
('simg records'),
('simian records'),
('sims records'),
('sinnbus'),
('sire london records'),
('sire records'),
('sister benten online'),
('situation two'),
('six degrees records'),
('six shooter records'),
('sixsevenine'),
('sixstepsrecords'),
('ska satellite records'),
('skam records'),
('skeleton crew'),
('skin graft records'),
('skint records'),
('skirl records'),
('skunk records'),
('sky and trees records'),
('sky records'),
('skybucket records'),
('skylite'),
('slam dunk records'),
('slampt'),
('slash records'),
('slate creek records'),
('slave pit records'),
('sledgehammer blues'),
('sleep it off records'),
('sleeping bag records'),
('slip-n-slide records'),
('siltbreeze'),
('slowdime records'),
('small stone records'),
('small wonder records'),
('smalltown america'),
('smalltown superjazzz'),
('smalltown supersound'),
('smash the house'),
('smash records'),
('smells like records'),
('smithsonian folkways recordings'),
('smoke-a-lot records'),
('snail records'),
('snakes & ladders records'),
('snapper music'),
('snotone'),
('so so def recordings'),
('sobe entertainment'),
('the social registry'),
('socialist roots sound system'),
('society recordings'),
('softdrive records'),
('solar records'),
('soleilmoon'),
('solid rock records'),
('solid state records (christian metal)'),
('solid state records (jazz)'),
('solitary man records'),
('soma records'),
('soma quality recordings'),
('some bizzare records'),
('some records'),
('sonablast! records'),
('sonar kollektiv'),
('song bird records'),
('sonic enemy'),
('sonic past music'),
('sonic unyon recording company'),
('sonic wave america'),
('sonic youth recordings'),
('sonic360 records'),
('sons ltd'),
('sony/atv music publishing'),
('sony bmg'),
('sony bmg masterworks'),
('sony classical records'),
('sony music entertainment'),
('sony music entertainment japan'),
('sony music india'),
('sony music special products'),
('sony records'),
('sony wonder'),
('sordide sentimental'),
('soul city records'),
('soul jazz records'),
('soulfuric recordings'),
('soulseek records'),
('sound circus'),
('sound document'),
('sound of gospel'),
('sound riot records'),
('sound stage 7'),
('sound system records'),
('sounds are active'),
('soundway records'),
('south indies'),
('southern empire records'),
('southern fried records'),
('southern lord records'),
('southern records'),
('southern studios'),
('southland records'),
('spaghetti records'),
('spalax'),
('spare me records'),
('spark records'),
('sparrow records'),
('sparrowheart music'),
('spartan records'),
('specialty records'),
('spectral sound'),
('speed label'),
('spiderleg records'),
('spin records (australia)'),
('spin records (us)'),
('spinalonga records'),
('spinart records'),
('spinefarm records'),
('spinnin'' records'),
('spinnup'),
('spirit zone records'),
('spit shine records'),
('spitfire records'),
('spivey records'),
('spoon records'),
('spotlite records'),
('spring hill music group'),
('springman records'),
('spv gmbh'),
('squint entertainment'),
('src records'),
('sst records'),
('st. george records'),
('staalplaat'),
('stage door records'),
('stamps-baxter music company'),
('stand up! records'),
('standard talking machine company'),
('standby records'),
('star music (philippines)'),
('star recordings'),
('star song communications'),
('star trak entertainment'),
('starboy entertainment'),
('starday records'),
('stardust promotion'),
('starkland'),
('starr records'),
('starship entertainment'),
('starstream records'),
('startime international'),
('states records'),
('stateside records'),
('static caravan recordings'),
('stax records'),
('stc recordings'),
('stealth records'),
('steed records'),
('steel tiger records'),
('steelpride records'),
('steeltown records'),
('steelwork maschine'),
('step one records'),
('stereolaffs'),
('sterile records'),
('sterling records (sweden)'),
('sterling records (us)'),
('sterno records'),
('stickfigure records'),
('stiff records'),
('stigmata'),
('stillborn records'),
('stmpd rcrds'),
('stockfisch records'),
('stockholm records'),
('stomp records'),
('stone records'),
('stone''d records'),
('stones throw records'),
('stony plain records'),
('storch music company'),
('storyville records'),
('storyville records (george wein''s)'),
('straight records'),
('strange famous records'),
('strange fruit records'),
('strange music'),
('strange ways'),
('strata-east records'),
('strata music'),
('streetsounds'),
('streetsweepers entertainment'),
('strictly rhythm'),
('studio !k7'),
('studio one'),
('studioseven recordings'),
('stunt records'),
('suave house records'),
('sub city records'),
('sublime records'),
('sub pop'),
('sub rosa'),
('sub verse records'),
('subconscious communications'),
('sublime frequencies'),
('subliminal'),
('submerged records'),
('subplate records'),
('subterranean records'),
('suburban base'),
('suburban home records'),
('suburban noize records'),
('suburban records'),
('suburban sprawl music'),
('such-a-punch media'),
('suckapunch records'),
('sudden death records'),
('sue records'),
('sugar hill records (bluegrass)'),
('sugar hill records (rap)'),
('suleputer'),
('sumerian records'),
('summersteps records'),
('summit records'),
('sumthing distribution'),
('sun records'),
('suncity records'),
('sundazed records'),
('sunflower records'),
('sunset alliance'),
('sunset records'),
('sunshine records (australia)'),
('sunshine records (usa)'),
('suntrip records'),
('suomen musiikki'),
('super records'),
('supernal music'),
('supersoul records'),
('supertone records'),
('supraphon')
go
INSERT INTO dbo.Label VALUES
('supreme records (grey gull subsidiary)'),
('supreme records (los angeles)'),
('supreme records (pama subsidiary)'),
('supreme records uk'),
('surfdog records'),
('surprise attack records'),
('surprise records'),
('survivor records'),
('sussex records'),
('sutemos'),
('sutton records'),
('suzy'),
('svr producciones'),
('swallow records'),
('swami records'),
('swan records (philadelphia, pa)'),
('swan records (jazz label)'),
('swan song records'),
('sweet lucy records'),
('swing time records'),
('swishahouse'),
('sword records'),
('syco music'),
('sympathy for the record industry'),
('synthetic sounds'),
('system recordings'),
('sahko recordings'),
('t.a. music'),
('t-neck records'),
('t-series'),
('taang! records'),
('table of the elements'),
('tabu recordings'),
('tabu records'),
('tag recordings'),
('take fo'' records'),
('takeover records'),
('takoma records'),
('talitres'),
('talkin'' loud'),
('talos records'),
('tamla records'),
('tangerine records (1963) (us)'),
('tangerine records (1992) (uk)'),
('tankcrimes'),
('tanza (new zealand)'),
('tapete records'),
('tara music label'),
('tarantulas records'),
('tarantura'),
('taste media'),
('tayster and rojac records'),
('tcr'),
('tea pot records'),
('team love'),
('tee pee records'),
('tee productions'),
('tee records'),
('teem records'),
('teenage usa recordings'),
('teenbeat records'),
('teichiku records'),
('telarc international corporation'),
('teldec record service'),
('teleprompt records'),
('tellus audio cassette magazine'),
('telstar records'),
('tempa'),
('temple records (1978 uk label)'),
('temple records (1984 uk label)'),
('temple us records'),
('tempo records (uk)'),
('tempo records (us)'),
('temporary music'),
('temporary residence limited'),
('ten music group'),
('ten12 records'),
('tender loving empire'),
('tennessee records'),
('tent show records'),
('terror squad'),
('tesco organisation'),
('test tube records'),
('testament records (uk)'),
('testament records (usa)'),
('tetragrammaton records'),
('tetrapod spools'),
('texas hotel records'),
('thee sheffield phonographic corporation'),
('thick records'),
('thick syrup records'),
('think music records'),
('thinner'),
('third man records'),
('third mind records'),
('thirsty ear recordings'),
('this is american music'),
('thizz entertainment'),
('three gut records'),
('three one g'),
('threshold house'),
('threshold records'),
('thrill jockey'),
('thump records'),
('tiara records'),
('tico records'),
('tiger lily records'),
('tiger style records'),
('tigerbeat6'),
('tigersushi records'),
('tigertrap records'),
('timberyard records'),
('time bomb recordings'),
('time-lag records'),
('time-life'),
('time records'),
('tino corp.'),
('tiny dog records'),
('tiny evil records'),
('tirk records'),
('titanic records'),
('tk records'),
('to the fallen records'),
('toast hawaii'),
('todamerica records'),
('toes in the sand recordings'),
('tofu records'),
('tokuma shoten'),
('tokyo dawn records'),
('tollie records'),
('tomato head records'),
('tombstone records'),
('tomlab'),
('tommy boy records'),
('tompkins square records'),
('too pure'),
('tooth & nail records'),
('top dawg entertainment'),
('top rank records'),
('topic records'),
('topten'),
('toshiba-emi'),
('tot ou tard'),
('touch and go records'),
('touch records'),
('tower records'),
('tr1be records'),
('track records'),
('trademark of quality'),
('tradisom'),
('tradition records'),
('trance syndicate'),
('trans continental records'),
('transatlantic records'),
('transcopic records'),
('transgressive records'),
('transmat'),
('transmission communications'),
('trash aesthetics'),
('trash art!'),
('trattoria records'),
('traum schallplatten'),
('trauma records'),
('trax records'),
('trekky records'),
('trend is dead! records'),
('trend records'),
('trensmat records'),
('trente oiseaux'),
('tres records'),
('tresor'),
('trial & error records'),
('tribe records'),
('tribe records (no)'),
('la tribu'),
('tribute records'),
('trickdisc recordings'),
('trifekta'),
('trikont'),
('trill entertainment'),
('triple crown records'),
('trisol music group'),
('triumph records (uk)'),
('triumph records (us)'),
('trix records'),
('trojan records'),
('troubleman unlimited records'),
('trout music'),
('tru''dat'' entertainment'),
('tru thoughts'),
('truck records'),
('true north records'),
('true tone records'),
('trumpet records'),
('trumpet swan productions'),
('trunk records'),
('trust in trance records'),
('trustkill records'),
('try me records'),
('tsop records'),
('tsr records'),
('tuff gong'),
('tug records'),
('tumi music'),
('tumult records'),
('tunnel records'),
('tutl'),
('tvt records'),
('twin/tone records'),
('twisted nerve records'),
('twisted records (uk)'),
('twisted records (us)'),
('tyscot records'),
('tzadik records'),
('ubiquity records'),
('ugly man records'),
('ugly nephew records'),
('uhd&c record company'),
('ujikaji'),
('uk records'),
('ultimae records'),
('the ultimate group'),
('ultra records'),
('umami records'),
('umtv'),
('unable records'),
('unart records'),
('uncensored records'),
('uncle howie records'),
('unda k9 records'),
('under one flag'),
('undercover prodigy'),
('undergroove records'),
('underground operations'),
('underground resistance'),
('unesco collection'),
('unfd'),
('unholy records'),
('uni records'),
('unicorn digital'),
('unicorn-kanchana'),
('unidisc music inc.'),
('the unilalia group'),
('union city recordings'),
('union label group'),
('united artists records'),
('united masters'),
('united records'),
('united records (1910s)'),
('united telefilm records'),
('universal classics group'),
('universal edition'),
('universal motown records group'),
('universal music group'),
('universal music india'),
('universal music latin entertainment'),
('universal records'),
('universal south records'),
('university recording company'),
('univision music group'),
('unlockedgroove'),
('unstable ape records'),
('up above records'),
('up records'),
('upfront records'),
('uppity cracker'),
('uprising records'),
('upsetter records (jamaica)'),
('upsetter records (usa)'),
('upside records'),
('uptown records'),
('urban jungle'),
('urban records'),
('urbnet records'),
('urgent! records'),
('urinine records'),
('us records'),
('utech records'),
('utopia records'),
('utp records'),
('uzi suicide'),
('v2 records'),
('v-disc'),
('v.i.p. records'),
('v/vm test records'),
('vagrant records'),
('valcour records'),
('valiant records'),
('valley entertainment'),
('valley records'),
('valve records'),
('van dyke records'),
('vandit'),
('vanguard records'),
('vap (video & audio project)'),
('varese-sarabande records'),
('vaws (verlag und agentur werner symanek)'),
('vde-gallo records'),
('veb deutsche schallplatten'),
('vee-jay records'),
('velour recordings'),
('velvet blue music'),
('velvet tone records'),
('vena records'),
('vendetta records'),
('vendlus records'),
('verity records'),
('vermin scum'),
('vertigo records'),
('verve records'),
('very good beats'),
('very small records'),
('vi music'),
('vicious vinyl'),
('victoria records (1952)'),
('victory records'),
('vik. recordings'),
('vik records'),
('villar records'),
('vim records'),
('vinyl solution'),
('the viper label'),
('virgin records'),
('virgin schallplatten'),
('virt records'),
('v.i.s.a.'),
('visible noise'),
('vision quest records'),
('vitamin records'),
('viva records'),
('viva records (philippines)'),
('vocalion records'),
('vogue records'),
('voiceprint records'),
('voices of wonder'),
('volcano entertainment'),
('volcom entertainment'),
('volition records'),
('volt records'),
('vox records'),
('vox records (germany)'),
('vp records'),
('wackies'),
('waerloga records'),
('wagram music'),
('waldorf music hall records'),
('wall of sound'),
('wallis original records'),
('walt disney records'),
('wand records'),
('wanker records'),
('warcon enterprises'),
('warm fuzz records'),
('warm records'),
('warner alliance'),
('warner curb records'),
('warner music australasia'),
('warner music canada'),
('warner music group'),
('warner records'),
('warner-spector records'),
('warp records'),
('warwick records (united kingdom)'),
('warwick records (united states)'),
('water lily acoustics'),
('waterbug records'),
('waterfront records'),
('watermelon records'),
('watertower music'),
('wau! mr. modo recordings'),
('waveform records'),
('wave music'),
('wax trax! records'),
('waxploitation records'),
('we the best music'),
('we put out records'),
('we r music'),
('weathermaker music'),
('web entertainment'),
('webco records'),
('wedge records'),
('weed records'),
('weewerk'),
('welk music group'),
('de werf'),
('wergo'),
('werk discs'),
('west craft records'),
('west records'),
('westbound records'),
('westminster records'),
('westpark music'),
('westport records'),
('westside records'),
('wgns recordings'),
('what have you records'),
('what records'),
('what? records'),
('whirlin'' disc records'),
('white noise records'),
('white pine music'),
('white whale records'),
('whitehaus family record'),
('whitfield records'),
('why not records'),
('wichita recordings'),
('wiiija'),
('wilbury records'),
('wild pitch records'),
('wild rags'),
('wildside records'),
('wildstar records'),
('willowtip records'),
('wind music'),
('wind-up records'),
('windfall records'),
('windham hill records'),
('wing records'),
('the winner records'),
('winter & winter'),
('witches brew'),
('wm recordings'),
('wmot records'),
('wolv records'),
('wooden nickel records'),
('woodrich records'),
('woodsist'),
('woodworm records'),
('woof records'),
('woollim entertainment'),
('word records'),
('work records'),
('workerbee records'),
('workshop jazz records'),
('world circuit'),
('world domination recordings'),
('world record club'),
('world serpent distribution'),
('wounded bird records'),
('wow music'),
('wrasse records'),
('wtii records'),
('wwe records'),
('wy records'),
('wyncote records'),
('wynona records'),
('xanadu records'),
('xemu records'),
('xenophile records'),
('xiii bis records'),
('xl recordings'),
('xo records'),
('xpressway'),
('xtra mile recordings'),
('xtreem music'),
('xyz records'),
('y records'),
('yambo records'),
('yazoo records'),
('yb music'),
('ybnl nation'),
('year0001'),
('yellow tail records'),
('yellow van records'),
('yep roc records'),
('yer bird records'),
('yg entertainment'),
('yoshitoshi records'),
('young god records'),
('young money entertainment'),
('yuletide records'),
('zarape records'),
('zarjazz'),
('ze records'),
('zebra records'),
('zee music company'),
('zell''s records'),
('zero musique'),
('zero records'),
('zoom lens'),
('zone 4'),
('zonophone records'),
('zoo entertainment'),
('zoth ommog records'),
('ztt records'),
('zunior'),
('zyx music'),
('1-2-3-4 go! records'),
('2.13.61'),
('2 tone records'),
('3 beat records'),
('3cg records'),
('3d vision records'),
('4ad'),
('4 star records'),
('5 minute walk'),
('5 rue christine'),
('7th magnitude'),
('8bitpeoples'),
('12 tonar'),
('12k'),
('13th planet records'),
('14th floor records'),
('16th avenue records'),
('19 recordings'),
('20th century fox records'),
('21st circuitry'),
('24 hour service station'),
('33rd street records'),
('50 records'),
('50 skidillion watts'),
('75 ark'),
('77 records'),
('88rising'),
('99 records'),
('143 records'),
('300 entertainment'),
('301studios'),
('415 records'),
('430 west records'),
('504 records'),
('550 music'),
('604 records'),
('625 thrashcore'),
('679 artists'),
('960 music group'),
('1017 records'),
('1605'),
('1965 records')